sudo: required

language: cpp

compiler:
  - gcc
  - clang

arch:
  - amd64
  - ppc64le
services:
  - docker

env:
  - TEST_OS=fedora-31 SANITIZE=address,undefined COVERALLS=0
  - TEST_OS=fedora-30 SANITIZE=address,undefined COVERALLS=0
  - TEST_OS=ubuntu-disco SANITIZE=address,undefined COVERALLS=0
  - TEST_OS=ubuntu-bionic SANITIZE=address,undefined COVERALLS=0
  - TEST_OS=ubuntu-bionic SANITIZE=none COVERALLS=1

matrix:
    exclude:
      - compiler: clang
        env: TEST_OS=ubuntu-bionic SANITIZE=none COVERALLS=1

before_install:
  - ci/test.sh build $TEST_OS

script:
  - ci/test.sh run $TEST_OS
